### ISSUE TITLE
Expand/collapse icon rotation wrong in material theme

### ISSUE THREAD

**Issue by srijken** [vaadin/vaadin-details#6]
In the material theme the chevron-right that is used points down for the expand action (correct), and to the right for the collapse action (should be up)

The rotation changes between 90deg (down) and 270deg (up), but when the panel is opened, the lumo style also leaks in, causing an additional 90deg rotation, resulting in 360deg rotation total.

**Comment by web-padawan** [comment]
Just to clarify: are you importing both Lumo and Material versions of the `vaadin-details`?

In general, Lumo and Material are not expected to be used in the same app, as that might result in unexpected style overrides here and there, due to the CSS specificity.

Note that we are also running visual regression tests agains each theme separately.
